/*
Script generated by Aqua Data Studio 19.0.0 on May-02-2018 11:34:14 AM
Database: test
Schema: <All Schemas>
Objects: COLLECTION, VIEW, INDEX
*/
DROP COLLECTION "orders";
DROP COLLECTION "map_reduce_example";
DROP COLLECTION "inventory";
DROP COLLECTION "dec128test";

CREATE COLLECTION "dec128test" ;
CREATE COLLECTION "inventory" ;
CREATE COLLECTION "map_reduce_example" ;
CREATE COLLECTION "orders" ;

INSERT INTO "dec128test"("_id", "colNumDecimal")
  VALUES(OBJECTID('5a7d641b46936c56bc5fd30d'), NumberDecimal("999999.49999999"));
INSERT INTO "inventory"("_id", "item", "price", "quantity")
  VALUES(1.0, 'The Scream', NumberDecimal("9.99"), 4.0);
INSERT INTO "map_reduce_example"("_id", "value")
  VALUES('abc123', 25.0);
INSERT INTO "orders"("_id", "cust_id", "ord_date", "status", "price", "items")
  VALUES(OBJECTID('59276c7a2330ef29a5e42033'), 'abc123', ISODATE('2012-10-04T07:00:00.000Z'), 'A', 25.0, [ { 'sku' : 'mmm', 'qty' : 5.0, 'price' : 2.5 }, { 'sku' : 'nnn', 'qty' : 5.0, 'price' : 2.5 } ]);
